// src/styles/colorThemes.ts

export const colourThemes = {
  classic: {
    background: '#1a1a2e',
    tileBackground: '#16213e',
    tileBorder: '#0f3460',
    tileText: '#e94560',
    headerText: '#f1f1f1',
    buttonBackground: '#0f3460',
    buttonText: '#f1f1f1',
  },
  neon: {
    background: '#2b2b2b',
    tileBackground: '#1e1e1e',
    tileBorder: '#00ff00',
    tileText: '#00ffff',
    headerText: '#ff00ff',
    buttonBackground: '#4a4a4a',
    buttonText: '#00ff00',
  },
  serene: {
    background: '#bfe3e8',
    tileBackground: '#dfe3e8',
    tileBorder: '#b0bec5',
    tileText: '#5f6c74',
    headerText: '#2c3e50',
    buttonBackground: '#b0bec5',
    buttonText: '#ffffff',
  },
  earthy: {
    background: '#d0e4de',
    tileBackground: '#c1d3c4',
    tileBorder: '#a4b8a6',
    tileText: '#4a5d23',
    headerText: '#3e5f40',
    buttonBackground: '#a4b8a6',
    buttonText: '#ffffff',
  },
  vibrant: {
    background: '#f5f5f5',
    tileBackground: '#ffeb3b',
    tileBorder: '#ff9800',
    tileText: '#4caf50',
    headerText: '#000000',
    buttonBackground: '#ff9800',
    buttonText: '#ffffff',
  },
  dusk: {
    background: '#2e3a40',
    tileBackground: '#3a4b53',
    tileBorder: '#1d2a34',
    tileText: '#c0c9d3',
    headerText: '#f5f5f5',
    buttonBackground: '#1d2a34',
    buttonText: '#c0c9d3',
  },
  sunset: {
    background: '#fff4e6',
    tileBackground: '#ffebcc',
    tileBorder: '#f4a261',
    tileText: '#d64f4f',
    headerText: '#2b2d2f',
    buttonBackground: '#f4a261',
    buttonText: '#ffffff',
  },
  pastel: {
    background: '#f0e6ef',
    tileBackground: '#fff0f5',
    tileBorder: '#c9ada7',
    tileText: '#4a4e69',
    headerText: '#22223b',
    buttonBackground: '#9a8c98',
    buttonText: '#f2e9e4',
  },
  oceanic: {
    background: '#e0f7fa',
    tileBackground: '#b2ebf2',
    tileBorder: '#4fc3f7',
    tileText: '#01579b',
    headerText: '#004d40',
    buttonBackground: '#4fc3f7',
    buttonText: '#ffffff',
  },
  retro: {
    background: '#faf3e0',
    tileBackground: '#f3e5ab',
    tileBorder: '#fbc02d',
    tileText: '#8d6e63',
    headerText: '#3e2723',
    buttonBackground: '#fbc02d',
    buttonText: '#ffffff',
  },
  forest: {
    background: '#e8f5e9',
    tileBackground: '#c8e6c9',
    tileBorder: '#a5d6a7',
    tileText: '#1b5e20',
    headerText: '#004d40',
    buttonBackground: '#a5d6a7',
    buttonText: '#ffffff',
  },
  coolMint: {
    background: '#e0f2f1',
    tileBackground: '#b2dfdb',
    tileBorder: '#4db6ac',
    tileText: '#004d40',
    headerText: '#00695c',
    buttonBackground: '#4db6ac',
    buttonText: '#ffffff',
  },
  warmEmber: {
    background: '#fff3e0',
    tileBackground: '#ffccbc',
    tileBorder: '#ff5722',
    tileText: '#bf360c',
    headerText: '#3e2723',
    buttonBackground: '#ff5722',
    buttonText: '#ffffff',
  },
}

export type ColourTheme = keyof typeof colourThemes
